{{- if .Values.api.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "vocab-app.fullname" . }}-api-pdb
  labels:
    app: api
spec:
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: api
{{- end }}
---
{{- if .Values.web.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "vocab-app.fullname" . }}-web-pdb
  labels:
    app: web
spec:
  minAvailable: {{ .Values.web.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: web
{{- end }}
